1. Create a NumPy array containing integers from 0 to 9.

In [21]:
import numpy as np
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
arr2=np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [7]:
arr3 = np.arange(0,9).reshape(3,3) 
arr3

arr3.shape
arr3.size

9

4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between
1 and 100, and print the shape and size.

In [22]:
arr5 = np.arange(1,10).reshape(3,3)
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

5. Create a 3x3 array of integers and access:
a. The second element of the first row.
b. The third column of the 2nd row.
c. A subarray with the first two rows and last two columns.

In [14]:
arr4 = np.random.randint(1,100,20).reshape(5,4)
print(arr4)
print(arr4.shape)
print(arr4.size)

[[ 5 54 95 93]
 [87 54 49  5]
 [46 63 55 19]
 [30 46 76  9]
 [26  6 81 90]]
(5, 4)
20


6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [21]:
arr5[0,1]
arr5[1,2]
arr5[0:2,1:3]

array([[2, 3],
       [5, 6]])

7. Reshape a 3x3 matrix into a 1D array.

In [31]:
arr6=np.arange(1,13)
print(arr6)
arr6.reshape(3,4)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
arr6=arr5.reshape(1,9)
print(arr6)

[[1 2 3 4 5 6 7 8 9]]


8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
subtraction, multiplication, and division on them.

In [47]:
ar1 = np.random.randint(1,10,6).reshape(2,3)
ar2 = np.random.randint(1,10,6).reshape(2,3)
add = ar1+ar2
sub=ar1-ar2
mul=ar1*ar2
div=ar1/ar2
print("addition : ")
print(add)
print("subtraction : ")
print(sub)
print("multiplication: ")
print(mul)
print("division : ")
print(div)



addition : 
[[10  4 13]
 [ 9 13 13]]
subtraction : 
[[ 8  0 -1]
 [-1  5  5]]
multiplication: 
[[ 9  4 42]
 [20 36 36]]
division : 
[[9.         1.         0.85714286]
 [0.8        2.25       2.25      ]]


9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a
given array.

In [53]:
summ=arr2.sum()
print("sum",summ)

avg=arr2.mean()
print("mean",avg)



sum 150
mean 30.0


10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
the @ operator.

In [6]:
import numpy as np

A = np.random.randint(1,5,4).reshape(2,2)
B=np.random.randint(1,10,4).reshape(2,2)
res1 = np.dot(A,B)
res2=A@B
print("matrix multiplication is np.dot : ",res1)
print("matrix multiplication is @ : ",res2)


matrix multiplication is np.dot :  [[27 54]
 [34 54]]
matrix multiplication is @ :  [[27 54]
 [34 54]]


11. Find the transpose of matrix A and matrix B.

In [10]:
A_T = A.T
B_T = B.T
print("matrix A :\n", A)
print("matrix B :\n", B)
print("Transpose of A:\n", A_T)
print("Transpose of B:\n", B_T)


matrix A :
 [[3 3]
 [4 2]]
matrix B :
 [[8 9]
 [1 9]]
Transpose of A:
 [[3 4]
 [3 2]]
Transpose of B:
 [[8 1]
 [9 9]]


12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
Explain how broadcasting works in this operation.

In [11]:
arr7 = np.random.randint(1,10,9).reshape(3,3)
oneD_arr = np.random.randint(1,4,3)
ans = arr7+oneD_arr

print("Matrix A:\n",arr7)
print("Array B:\n", oneD_arr)
print("Result:\n", ans)

Matrix A:
 [[6 3 9]
 [5 1 9]
 [4 2 9]]
Array B:
 [2 1 2]
Result:
 [[ 8  4 11]
 [ 7  2 11]
 [ 6  3 11]]


13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the
entire array. the 2D array.
Explain how broadcasting works in this operation.

In [16]:
arr = np.random.randint(1,20,16).reshape(4,4)
print(arr)
print("mean: " , arr.mean())
print("min : ",arr.min())
print("max",arr.max())



[[ 8 14 10 16]
 [19 19 12 16]
 [ 5 12  6  2]
 [ 3 10 14 13]]
mean:  11.1875
min :  2
max 19


14. Find the row-wise and column-wise sums.

In [17]:
row_sum = np.sum(arr,axis=1)
col_sum = np.sum(arr,axis=0)
print("Matrix A:\n", arr)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Matrix A:
 [[ 8 14 10 16]
 [19 19 12 16]
 [ 5 12  6  2]
 [ 3 10 14 13]]
Row-wise sum: [48 66 25 40]
Column-wise sum: [35 55 42 47]


15. Generate an array of 10 random integers between 1 and 50.

In [18]:
c=np.random.randint(1,50,10)
print(c)

[47 25 15 40  3 44 43  1 41 48]


16. Generate a 5x5 matrix of random floats between 0 and 1.

In [20]:
a = np.random.rand(5,5)
print(a)

[[0.56890941 0.53709523 0.7030665  0.77531624 0.23541102]
 [0.79344104 0.15439969 0.04122445 0.3675277  0.40167705]
 [0.83350865 0.94035906 0.52260077 0.47514473 0.96766122]
 [0.16146716 0.19550464 0.17685278 0.25732657 0.08756405]
 [0.67499993 0.92202072 0.69659447 0.76821887 0.70761691]]
