1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
import numpy as np

mat = np.arange(2,14).reshape(4,3)
mat

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

2. Write code to replace the odd numbers by -1 in the array created by using
random.randint( 1 , 50,20)

In [5]:
arr = np.random.randint(1,50,20)
arr1=arr
print(arr1)
for i in range (len(arr)):
    if arr[i] % 2 != 0 :
        arr[i]=-1

        
arr

[38 49 34  6 24  5 49 15  4 42 27 36 20 34  3 26 36 27 47  4]


array([38, -1, 34,  6, 24, -1, -1, -1,  4, 42, -1, 36, 20, 34, -1, 26, 36,
       -1, -1,  4], dtype=int32)

3. Perform the following operations on an array of mobile phones prices 6999, 7500,
11999, 27899, 14999, 9999.
a. Create a 1d-array of mobile phones prices
b. Convert this array to float type
c. Append a new mobile having price of 13999 Rs. to this array
d. Reverse this array of mobile phones prices
e. Apply GST of 18% on mobile phones prices and update this array.

In [19]:
ph =np.array([6999,7500,11999,27899,14999,9999])
print("original array " , ph)
float_arr = ph.astype(float)
print("float array " , float_arr)
ph=np.append(ph,13999)
print("updated array " , ph )

ph1=ph[::-1]
print("reversed array " , ph1)
up_ph =ph*18.8
up_ph



original array  [ 6999  7500 11999 27899 14999  9999]
float array  [ 6999.  7500. 11999. 27899. 14999.  9999.]
updated array  [ 6999  7500 11999 27899 14999  9999 13999]
reversed array  [13999  9999 14999 27899 11999  7500  6999]


array([131581.2, 141000. , 225581.2, 524501.2, 281981.2, 187981.2,
       263181.2])

f. Sort the array in descending order of price

In [20]:
import numpy as np

mobiles = np.array([11798.82, 17698.82, 23598.82, 16518.82])

mobiles = np.sort(mobiles)[::-1]

print(mobiles)


[23598.82 17698.82 16518.82 11798.82]


In [ ]:
What is the average mobile phone price

In [22]:
avg = ph.mean()
print(ph)
avg

[ 6999  7500 11999 27899 14999  9999 13999]


np.float64(13342.0)

In [23]:
mobiles = [11798.82, 17698.82, 23598.82, 16518.82]

max_price = mobiles[0]
min_price = mobiles[0]

for price in mobiles:
    if price > max_price:
        max_price = price
    if price < min_price:
        min_price = price

difference = max_price - min_price
print(difference)


11800.0


In [24]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)

print(indices[0])


[0 1 4]
